### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by XQYY** [RobustFieldAutonomyLab/Mission-Oriented-GP-Motion-Planning#1]
Hello, after successful compilation according to the requirements to run the test code, but reported this error, the operation failed, want to know the reason and solution, thank you very much.

~/Mission-Oriented-GP-Motion-Planning/build/tests$ ./testMobile3D ../../data/STR.yaml
testMobile3D: /home/yxq/gtsam-develop-linux/include/gtsam/3rdparty/Eigen/Eigen/src/Core/Redux.h:411: typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_min_op<double, double, 0>; Derived = Eigen::Matrix<double, -1, -1>; typename Eigen::internal::traits<T>::Scalar = double]: Assertion `this->rows()>0 && this->cols()>0 && "you are using an empty matrix"' failed.
已放弃 (核心已转储)

**Comment by yeweihuang** [comment]
The error is probably caused by passing an empty or invalid map file to the algorithm, I would recommend step into the code and check whether all paths are valid.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: XQYY ***@***.***>
Sent: Monday, August 5, 2024 10:08:24 AM
To: RobustFieldAutonomyLab/Mission-Oriented-GP-Motion-Planning ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RobustFieldAutonomyLab/Mission-Oriented-GP-Motion-Planning] Test failure (Issue #1)

CAUTION: This email originated from outside the organization. Please do not click links or open attachments unless you recognize the sender and know the content is safe.


Hello, after successful compilation according to the requirements to run the test code, but reported this error, the operation failed, want to know the reason and solution, thank you very much.

~/Mission-Oriented-GP-Motion-Planning/build/tests$ ./testMobile3D ../../data/STR.yaml
testMobile3D: /home/yxq/gtsam-develop-linux/include/gtsam/3rdparty/Eigen/Eigen/src/Core/Redux.h:411: typename Eigen::internal::traits::Scalar Eigen::DenseBase::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_min_op<double, double, 0>; Derived = Eigen::Matrix<double, -1, -1>; typename Eigen::internal::traits::Scalar = double]: Assertion `this->rows()>0 && this->cols()>0 && "you are using an empty matrix"' failed.
已放弃 (核心已转储)

―
